### Основы Numpy: массивы и векторные вычисления

In [3]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr * 2

2.17 ms ± 41.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit [x * 2 for x in my_list]

99.1 ms ± 2.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ndarray

In [8]:
data = np.array([[1.5,0,-0.1],[0,-3,6.5]])
data * 10, data + data

(array([[ 15.,   0.,  -1.],
        [  0., -30.,  65.]]),
 array([[ 3. ,  0. , -0.2],
        [ 0. , -6. , 13. ]]))

In [10]:
# dtype, shape
data.shape, data.dtype

((2, 3), dtype('float64'))

### Создание ndarray

In [12]:
data1 = [11,43,52,0,4.5]
arr1 = np.array(data1)
type(data1), type(arr1)
data1, arr1 

([11, 43, 52, 0, 4.5], array([11. , 43. , 52. ,  0. ,  4.5]))

In [22]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
# ndim
arr1.ndim, arr2.ndim

(1, 2)

функция np.array() сасмостоятельно определяет тип, если не указать самому

In [24]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

np.zeros, np.ones, np.empty

In [28]:
np.zeros(10)
np.zeros((2,3))
np.empty((3,5))

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        6.23053614e-307, 1.69121639e-306],
       [9.34613185e-307, 1.24610383e-306, 1.11259940e-306,
        1.60220393e-306, 8.01097889e-307],
       [1.37961234e-306, 1.78021527e-306, 8.34450230e-308,
        3.91792476e-317, 0.00000000e+000]])

 Функция numpy.arange – вариант встроенной в Python функции range, только 
возвращаемым значением является массив:

In [30]:
np.arange(10)
type(range(10)), type(np.arange(10))

(range, numpy.ndarray)

asarray, ones_like, zeros_like, empty_like, full, eye, identity

In [32]:
# np.eye(n, m=None, k=0)
np.eye(3)
#  То же, что np.eye(n), но только квадратную и без сдвигов.
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Типы данных для ndarray

In [35]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

int32 --> float64

In [38]:
arr = np.array([1,2,3,4,5])
float_arr = arr.astype(np.float64)
arr.dtype, float_arr.dtype

(dtype('int32'), dtype('float64'))

float64 --> int32

In [43]:
arr = np.array([3.7,-1.2,-2.6,4.5])
arr.astype(np.int32)

array([ 3, -1, -2,  4])

 Если имеется массив строк, представляющих целые числа, то astype позволит 
преобразовать их в числовую форму:

In [55]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype = np.string_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

Можно также использовать атрибут dtype другого массива

In [59]:
int_array = np.arange(10)
calibers = np.array([.22,.270,.357,.380,.44,.50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

!!  При вызове astype всегда создается новый массив (данные копи
руются), даже если новый dtype не отличается от старого

### Арифметические операции с массивами Numpy
Массивы важны, потому что позволяют выразить операции над совокупностя
ми данных без выписывания циклов for. Обычно это называется векториза
цией. Любая арифметическая операция над массивами одинакового размера 
применяется к соответственным элементам

In [62]:
arr = np.array([[1,2,3],[4,5,6]])
arr * arr 
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

 Арифметические операции, в которых участвует скаляр, применяются 
к каждому элементу массива:

In [65]:
1 / arr
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

Сравнение массивов одинакового размера дает булев массив

In [66]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])