### Основы Numpy: массивы и векторные вычисления

In [3]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr * 2

2.17 ms ± 41.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit [x * 2 for x in my_list]

99.1 ms ± 2.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ndarray

In [8]:
data = np.array([[1.5,0,-0.1],[0,-3,6.5]])
data * 10, data + data

(array([[ 15.,   0.,  -1.],
        [  0., -30.,  65.]]),
 array([[ 3. ,  0. , -0.2],
        [ 0. , -6. , 13. ]]))

In [10]:
# dtype, shape
data.shape, data.dtype

((2, 3), dtype('float64'))

### Создание ndarray

In [12]:
data1 = [11,43,52,0,4.5]
arr1 = np.array(data1)
type(data1), type(arr1)
data1, arr1 

([11, 43, 52, 0, 4.5], array([11. , 43. , 52. ,  0. ,  4.5]))

In [22]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
# ndim
arr1.ndim, arr2.ndim

(1, 2)

функция np.array() сасмостоятельно определяет тип, если не указать самому

In [24]:
arr1.dtype, arr2.dtype

(dtype('float64'), dtype('int32'))

np.zeros, np.ones, np.empty

In [28]:
np.zeros(10)
np.zeros((2,3))
np.empty((3,5))

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        6.23053614e-307, 1.69121639e-306],
       [9.34613185e-307, 1.24610383e-306, 1.11259940e-306,
        1.60220393e-306, 8.01097889e-307],
       [1.37961234e-306, 1.78021527e-306, 8.34450230e-308,
        3.91792476e-317, 0.00000000e+000]])

 Функция numpy.arange – вариант встроенной в Python функции range, только 
возвращаемым значением является массив:

In [30]:
np.arange(10)
type(range(10)), type(np.arange(10))

(range, numpy.ndarray)

asarray, ones_like, zeros_like, empty_like, full, eye, identity

In [32]:
# np.eye(n, m=None, k=0)
np.eye(3)
#  То же, что np.eye(n), но только квадратную и без сдвигов.
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Типы данных для ndarray